config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_app.urls')),
    path('taskrabbits/', include('rabbits_app.urls')),
    path("convert/", include("guest_user.urls")),
]

rabbits_app/urls.py
from django.urls import path
from . import views

app_name = 'rabbits_app'
urlpatterns = [
    path('create/', views.create_rabbit, name='create_rabbit'),
    path('edit/<str:name>', views.edit_rabbit, name='edit_rabbit'),
    path('delete/<str:title>', views.delete_rabbit, name='delete'),
    path('emergencybuttonwipe/', views.emergency_button_wipe, name='emergencybuttonwipe'),
    
 
]

user_app/urls.py
from django.urls import path
from . import views

app_name = 'users_app'
urlpatterns = [
    path('', views.index , name="index"),
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('interface/', views.interface, name='interface'),
]

rabbits_app/models.py
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# from colorfield.fields import ColorField


class Rabbit(models.Model):
    user = models.ForeignKey(User,  default=None, on_delete=models.CASCADE)
    links = models.CharField(max_length=999999)
    title = models.CharField(max_length=12)
    color = models.CharField(max_length=15)
    def __str__(self):
        return f"{self.user} - {self.title} - {self.links} - {self.color}"

user_app/models.py
from django.db import models

# Create your models here.

rabbits_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from django.forms.widgets import TextInput

class CreateRabbitForm(forms.ModelForm):
    title = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': "name"}))
    
    class Meta:
        model = Rabbit
        fields = '__all__'
        exclude = ['user', 'links']
        widgets ={
           
            'color': TextInput(attrs={'type':'color'}),

            }

user_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class SignupForm(forms.Form):
    username = forms.CharField(label='', max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}), label='', max_length=10,)
    
class LoginForm(forms.Form):
    username = forms.CharField(label='', max_length=20, widget=forms.TextInput(attrs={'placeholder': ' Your Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': ' Your Password'}), label='', max_length=10,)

rabbits_app/views.py
from ast import mod
from typing import final
from django.shortcuts import render
from .models import *
from .forms import *
from django.http import HttpResponseRedirect
from django.urls import reverse
from guest_user.decorators import allow_guest_user
# Create your views here.

@allow_guest_user
def create_rabbit(request):
    if request.method == 'GET':
        form = CreateRabbitForm()
        context = {
            'form': form
        }
        return render(request, 'rabbit_temps/createrabbit.html', context)
    elif request.method == 'POST':

        link_list = [] # Organized form data into list
        print(len(request.POST)-2)
        for input in range(len(request.POST)-3): # Allows user to add as many sites as they want
            link_list.append(request.POST[f'site-{input+1}'])

        print(link_list)        
        # Checks to see if any feilds empty
        final_links = ""
        for web in link_list:
            if web != '':
                final_links += f",{web}"
        
        if final_links[0] == ',':
                final_links = final_links[1:]
    
        new_rabbit = Rabbit(user=request.user, title=request.POST['title'], links=final_links, color=request.POST['color'])
        new_rabbit.save()
        return HttpResponseRedirect(reverse('users_app:interface'))
@allow_guest_user
def edit_rabbit(request, name):
    if request.method == 'GET':
        model_data = Rabbit.objects.filter(title=name)

        for data in model_data:
            split_links = data.links.split(',')
        
        context = {
            'model_data': model_data,
            'links' : split_links,
            'color': model_data[0].color
        }
        return render(request, 'rabbit_temps/editrabbit.html', context)
    elif request.method == 'POST':

        print(request.POST)
        model_data = Rabbit.objects.get(title=name)
        model_data.title = request.POST['title']
        model_data.color = request.POST['color']

        link_list = []
        for sitenum in request.POST:
            
            if sitenum[0] =='s':
                link_list.append(request.POST[sitenum])


    
        # Checks to see if any feilds empty
        final_links = ""
        for web in link_list:
            if web != '':
                final_links += f",{web}"
        
        if final_links[0] == ',':
                final_links = final_links[1:]
    
        model_data.links = final_links

        model_data.save()
        return HttpResponseRedirect(reverse('users_app:interface'))

@allow_guest_user
def delete_rabbit(request, title):
        rabbit_begone = Rabbit.objects.filter(title=title)
       
        rabbit_begone.delete()
        return HttpResponseRedirect(reverse('users_app:interface'))

def emergency_button_wipe(request):
    Rabbit.objects.all().delete()
    return HttpResponseRedirect(reverse('users_app:index'))

user_app/views.py
from django.shortcuts import render
from .forms import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from rabbits_app.models import *
# Create your views here.
from guest_user.decorators import allow_guest_user

# @allow_guest_user
def index(request):
    
    return render(request, 'base_temps/index.html', )

@allow_guest_user
def interface(request):
    rabbits_model = Rabbit.objects.filter(user=request.user)
    rabbits = {}
    for index, link_list in enumerate(rabbits_model):
        conversion = rabbits_model[index].links.split(',')
        rabbits[rabbits_model[index].title] = [conversion, rabbits_model[index].color]
        
    
    context = {
        "rabbit_list": rabbits
    }

    return render(request, 'base_temps/interface.html', context)


def signup(request):
    if request.method == 'GET':
        sign_form = SignupForm()
        context = {
        'sign_form': sign_form
        }
        return render(request, 'base_temps/signup.html', context)

    elif request.method == 'POST':
        form_data = SignupForm(request.POST)

        if form_data.is_valid():
            new_user = User.objects.create_user(
                username = form_data.cleaned_data['username'],
                password = form_data.cleaned_data['password'],
             
            )
            sign_user = authenticate(username=form_data.cleaned_data['username'], password=form_data.cleaned_data['password'])
            login(request, new_user, backend='django.contrib.auth.backends.ModelBackend')
    return HttpResponseRedirect(reverse('users_app:interface'))

def user_login(request):
    if request.method == 'GET':
        log_form = LoginForm()
        context = {
            'log_form': log_form
        }
        return render(request, 'base_temps/login.html', context)
    elif request.method == 'POST':
        log_form = LoginForm(request.POST)
        if log_form.is_valid():
            password = log_form.cleaned_data['password']
            username = log_form.cleaned_data['username']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('users_app:interface'))
            else:
                # Checks if user exists
                log_form.add_error('username', 'Invalid email or password')
                return render(request, 'base_temps/login.html', {'log_form': log_form})

    return render(request, 'base_temps/login.html')

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('users_app:index'))

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/base_temps/index.html
{% extends 'base.html' %} 
{% block title %}TaskRabbit{% endblock %}
{% block content %}
{% load static %}

<div id="index-content"> 

    <div id="index-title">
        <div id="word-wrap">
            <h1>RABBIT</h1>
            <h1>TASK</h1>
        </div>
    </div>
    
    
    <a id="github-wrap" style="z-index: 2;" href="https://github.com/Gage-Lieble/TaskRabbit"><img src="{% static 'imgs/github.svg' %}" alt=""></a>
 
    
    {% if user.is_authenticated %}
    <div class="btn-wrap">
    <a class="index-btn" href="{% url 'users_app:interface' %}">INTERFACE</a>
    <a class="index-btn" href="{% url 'users_app:logout' %}">LOGOUT</a>
    <a class="index-btn" href="https://www.gagelieble.com/">PORTFOLIO</a>
    </div>
        
        {% else %}
    <div class="btn-wrap">
        <a class="index-btn" href="{% url 'users_app:interface' %}">GUEST LOGIN</a>
        <a class="index-btn" href="{% url 'users_app:signup' %}">SIGNUP</a>
        <a class="index-btn" href="{% url 'users_app:login' %}">LOGIN</a>
    </div>
    {% endif %}

</div>

    
{% endblock %}

templates/base_temps/interface.html
<!-- @html-nocheck -->
{% extends 'base.html' %}


{% block title %}TaskRabbit - Interface{% endblock %}
{% block content %}

<div id="greet-title">
    <h3 class="head-word">GREETINGS </h3>
    <h1 class="head-word">{{ request.user }}</h1>
</div>

<div id="interface-btns-wrap">
    
    {% if rabbit_list|length == 0  %}
        <h2 style="text-align: center; width: 100vw; margin-top: 25vh;">You have no buttons</h2>
        {% else %}

        {% for key, values in rabbit_list.items %}
        <div style="border-top: 6px solid {{values.1}};"  class="link-btn-wrap">
            <h3 id="btn" onclick="openLinks({{values.0}})">{{key}}</h3>
            <div class="edit-btn-wrap">
                <a class="edit-btn" style="background-color: {{values.1}};" href="{% url 'rabbits_app:edit_rabbit' key %}">EDIT</a>
                <a class="edit-btn" style="background-color: {{values.1}};" href="{% url 'rabbits_app:delete' key %}">DELETE</a>
    
            </div>
        </div>
        {% endfor %}
    {% endif %}
        
    
</div>

<div id="nav-wrapper">
    
    <a class="nav-btns" href="{% url 'users_app:index' %}">HOME</a>
    <a id="create-btn" href="{% url 'rabbits_app:create_rabbit' %}">CREATE +</a>
    <a class="nav-btns" href="{% url 'users_app:logout' %}">LOGOUT</a>
</div>


    

{% endblock %}

templates/base_temps/login.html
{% extends 'base.html' %}
{% block title %}TaskRabbit - Login{% endblock %}
{% block content %}

<div id="greet-title-sign">
    <h3 class="head-word">LOGIN</h3>
</div>
<form action="" method="POST">
    {% csrf_token %}
    <div id="sign-form-wrap">
        {{log_form}}
        <a href="{% url 'users_app:signup' %}" style="color: white; text-decoration: none; font-size: 15px">signup instead</a>
    </div>
   
    <div id="nav-wrapper">
        <a id="edit-back" href="{% url 'users_app:index' %}">GO HOME</a>
        <button class="form-submit-btn" style="color: black;" type="submit">LOGIN</button>
    </div>
</form>

{% endblock %}

templates/base_temps/signup.html
{% extends 'base.html' %}

{% block title %}TaskRabbit - Signup{% endblock %}
{% block content %}
<div id="greet-title-sign">
    <h3 class="head-word">SIGN UP</h3>
</div>
<form action="{% url 'users_app:signup' %}" method="POST">
    {% csrf_token %}
    <div id="sign-form-wrap">
        {{ sign_form }}
        <a href="{% url 'users_app:login' %}" style="color: white; text-decoration: none; font-size: 15px">login instead</a>
    </div>
        <div id="nav-wrapper">
            <a id="edit-back" href="{% url 'users_app:index' %}">GO HOME</a>
            <button class="form-submit-btn" style="color: black;" type="submit">SIGN UP</button>
        </div>
    </form>

{% endblock %}

templates/rabbit_temps/createrabbit.html
{% extends 'rabbitbase.html' %}

{% block title %}TaskRabbit - Create{% endblock %}
{% block content %}

<body onload="getListLen(1)">
    
    <div id="greet-title">
        <h3 class="head-word">CREATING</h3>
        <h1 class="head-word" style="text-transform:lowercase; margin-bottom: 0px;">button</h1>
</div>
<form id="edit-form-create" action="{% url 'rabbits_app:create_rabbit' %}" method="POST">
    <h4>NAME</h4>
    {% csrf_token %}
    {{form}}
    <div id="create-form">
        <h4>LINKS</h4>
        <input class="edit-text" type="url" name="site-1" placeholder="your link" required>
    </div>
    <div id="nav-wrapper">
        <a id="edit-back" href="{% url 'users_app:interface' %}">GO BACK</a>
        <button class="form-submit-btn" style="background-color: white; color: black;" type="submit">CREATE</button>
        <div id="add_inp">LINK +</div>
    </div>
</form>

</body>
{% endblock %}

templates/rabbit_temps/editrabbit.html
{% extends 'rabbitbase.html' %}

{% block title %}TaskRabbit - Edit{% endblock %}
{% block content %}

<body onload="getListLen({{links|length}})">
<div id="greet-title">
    <h3 class="head-word">EDITING </h3>
    <h1 class="head-word" style="text-transform:lowercase; margin-bottom: 0px;">{{model_data.0.title}}</h1>
</div>


<form id="edit-form" action="{% url 'rabbits_app:edit_rabbit' model_data.0.title %}" method="POST">
    {% csrf_token %}
    <h4 style="margin-top: 0px;">NAME</h4>
    <input class="edit-text" type="text" name="title" value="{{model_data.0.title}}">
    <h4 style="margin-top: 0px;">COLOR</h4>
    <input type="color" class="color-field" name="color" value="{{color}}">
    
    <div id="create-form">
        <h4>LINKS</h4>
        {% for link in links  %}
            <input class="edit-text" type="url" name="site-{{forloop.counter}}" value="{{link}}" required>
        {% endfor %}
    </div>
        
    
<div id="nav-wrapper">
    <a id="edit-back" href="{% url 'users_app:interface' %}">GO BACK</a>
    <button class="form-submit-btn" style="background-color: {{model_data.0.color}};" type="submit">SAVE</button>
    <div id="add_inp">LINK +</div>
</div>
<a class="edit-btn" style="background-color:red;" href="{% url 'rabbits_app:delete' model_data.0.title %}">!DELETE BUTTON!</a> 
</form>

</body>
{% endblock %}

templates/rabbitbase.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>

    {% block content %}
    {% endblock %}

</html>